routes/web.php
<?php

use App\Http\Controllers\Admin\AdminCategoryController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminNewsController;
use App\Http\Controllers\Admin\AdminPersonController;
use App\Http\Controllers\Admin\ParserController;
use App\Http\Controllers\CategoryNewsController;
use App\Http\Controllers\CommentNewsController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\OneCategoryNewsController;
use App\Http\Controllers\OneNewsController;
use App\Http\Controllers\PersonAccountController;
use App\Http\Controllers\PersonalAccountController;
use App\Http\Controllers\SocialController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/personal', [PersonAccountController::class, 'personalForm'])->name('personal_form');
Route::post('/personal', [PersonAccountController::class, 'update'])->name('update');

Route::group(['prefix'=>'social'], function (){
   Route::post('/login', [SocialController::class, 'loginSocial'])->name('login_social');
   Route::get('/response', [SocialController::class, 'responseVK'])->name('response_vk');
   Route::get('/responseFB', [SocialController::class, 'responseFB'])->name('response_fb');
});


Route::get('/', [Controller::class, 'index'])->name('home_all');
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/category/{id}', [OneCategoryNewsController::class, 'oneCategory'])->name('one_category');
Route::get('/category', [CategoryNewsController::class, 'category'])->name('all_category');
Route::get('/{idNews}', [OneNewsController::class, 'oneNews'])->name('one_news');
Route::get('/locale/{locale}', [Controller::class, 'changeLocale'])->name('locale');

Route::middleware('auth')
    ->group(function () {
        Route::get('/comment/{newsID}', [CommentNewsController::class, 'showForm'])->name('show_form');
        Route::post('/comment', [CommentNewsController::class, 'comment'])->name('comment');
    });

Route::middleware('role:admin')
    ->prefix('admin')
    ->group(function () {
        Route::resource('news', AdminNewsController::class);
        Route::resource('category', AdminCategoryController::class);
        Route::resource('person', AdminPersonController::class);
        Route::get('index', [AdminController::class, 'index'])->name('home_admin');
        Route::get('parser', [ParserController::class, 'index'])->name('parser');
    });

resources/views/admin/categories.blade.php
@extends('layouts.app')

@section('content')
    <div class="introduction">
        <div class="introduction__item container">
            <h1 class="introduction__title">{{ __('admin/admin.title_categories') }}</h1>
        </div>
    </div>

    <div class="page__body container">
        <a href="{{ route('category.create') }}" class="transition-button">
            <span class="transition-button__text">{{ __('admin/buttons.button_add') }}</span>
        </a>
        <section class="news">
            @foreach($categories as $item)
                <div class="block-news">
                    <h2>{{$item->title}}</h2>
                    <div class="action">
                        <a href="{{ route('category.edit', $item->id) }}" class="transition-button">
                            <span class="transition-button__text">{{__('admin/buttons.button_edit')}}</span>
                        </a>

                        <form action="{{ route('category.destroy', $item->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="transition-button">{{__('admin/buttons.button_del')}}</button>
                        </form>
                    </div>
                </div>
            @endforeach
            {{ $categories->links() }}
        </section>
    </div>
@endsection

resources/views/admin/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="introduction">
        <div class="introduction__item container">
            <h1 class="introduction__title">{{__('admin/admin.title_index')}}</h1>
        </div>
    </div>

    <div class="page__body container-main">
        <h2>{{__('admin/admin.text')}}</h2>

        <div class="block-news">
            <p>{{__('admin/admin.select_category')}}</p>
            <a href="{{ route('category.index') }}" class="transition-button">
                <span class="transition-button__text">{{__('admin/buttons.button_category')}}</span>
            </a>
        </div>
        <div class="block-news">
            <p>{{__('admin/admin.select_news')}}</p>
            <a href="{{ route('news.index') }}" class="transition-button">
                <span class="transition-button__text">{{__('admin/buttons.button_news')}}</span>
            </a>
        </div>
        <div class="block-news">
            <p>{{__('admin/admin.select_person')}}</p>
            <a href="{{ route('person.index') }}" class="transition-button">
                <span class="transition-button__text">{{__('admin/buttons.button_person')}}</span>
            </a>
        </div>
    </div>

@endsection

resources/views/admin/newCategory.blade.php
@extends('layouts.app')

@section('content')

    <div class="introduction">
        <div class="introduction__item container">
            <h1 class="introduction__title">{{ isset($category) ? (__('admin/admin.title_change') . ' "' . $category->title . '"') :  __('admin/admin.title_add') }}</h1>
        </div>
    </div>
    <div class="page__body container">
        <div class="mt-8">
            <form class="space-y-5 mt-5" method="POST"
                  action="{{ isset($category) ? route('category.update', $category->id) : route('category.store') }}">
                @csrf

                @if(isset($category))
                    @method('PUT')
                @endif

                <input name="title" type="text"
                       class="w-full h-12 border border-gray-800 rounded px-3 @error('title') border-red-500 @enderror"
                       placeholder="{{__('admin/admin.placeholder_name')}}" value="{{ $category->title ?? '' }}"/>

                @error('title')
                <p class="text-red-500">{{ $message }}</p>
                @enderror


                <button type="submit" class="text-center w-full bg-blue-900 rounded-md text-white py-3 font-medium"
                        value="save">
                    {{__('admin/buttons.button_save')}}
                </button>
            </form>
        </div>

        <div class="transition">
            <a href="{{route('category.index')}}" class="transition-button">
                <span class="transition-button__text">{{__('admin/buttons.button_back')}}</span>
            </a>
        </div>
    </div>

@endsection

resources/views/admin/newNews.blade.php
@extends('layouts.app')

@section('content')

    <div class="introduction">
        <div class="introduction__item container">
            <h1 class="introduction__title">{{ isset($news) ? (__('admin/admin.title_edit_news') . ' "' . $news->title . '"') :  __('admin/admin.title_add_news') }}</h1>
        </div>
    </div>
    <div class="page__body container">
        <div class="mt-8">
            <form class="space-y-5 mt-5" method="POST"
                  action="{{ isset($news) ? route('news.update', $news->id) : route('news.store') }}">
                @csrf

                @if(isset($news))
                    @method('PUT')
                @endif

                @if(is_int($category))
                    <input hidden type="checkbox" name="category_id" value="{{$category}}" checked>
                @else
                    <select name="category_id" class="w-full h-12 border border-gray-800 rounded px-3">
                        <option disabled>{{__('option_select_category')}}</option>
                        @foreach($category as $item)
                            <option value="{{$item->id}}">{{$item->title}}</option>
                        @endforeach
                    </select>


                @endif


                <input name="title" type="text"
                       class="w-full h-12 border border-gray-800 rounded px-3 @error('title') border-red-500 @enderror"
                       placeholder="{{__('admin/admin.placeholder_name')}}" value="{{ $news->title ?? '' }}"/>

                @error('title')
                <p class="text-red-500">{{ $message }}</p>
                @enderror

                <input name="description" type="text"
                       class="w-full h-12 border border-gray-800 rounded px-3 @error('description') border-red-500 @enderror"
                       placeholder="{{__('admin/admin.placeholder_description')}}"
                       value="{{ $news->description ?? '' }}"/>

                @error('description')
                <p class="text-red-500">{{ $message }}</p>
                @enderror

                <textarea name="news_body"
                          class="w-full h-12 border border-gray-800 rounded px-3 @error('news_body') border-red-500 @enderror"
                          placeholder="{{__('admin/admin.placeholder_text')}}"
                >{{ $news->news_body ?? '' }}</textarea>

                @error('news_body')
                <p class="text-red-500">{{ $message }}</p>
                @enderror

                <input type="date" name="publish_date">

                @error('publish_date')
                <p class="text-red-500">{{ $message }}</p>
                @enderror

                <button type="submit" class="text-center w-full bg-blue-900 rounded-md text-white py-3 font-medium"
                        value="save">
                    {{__('admin/buttons.button_save')}}
                </button>
            </form>
        </div>

        <div class="transition">
            <a href="{{$route}}" class="transition-button">
                <span class="transition-button__text">{{$title_button}}</span>
            </a>
        </div>
    </div>

@endsection

resources/views/admin/newPerson.blade.php
@extends('layouts.app')

@section('content')

    <div class="introduction">
        <div class="introduction__item container">
            <h1 class="introduction__title">{{ isset($person) ? (__('admin/admin.title_edit_person') . ' "' . $person->name . '"') :  __('admin/admin.title_add_person') }}</h1>
        </div>
    </div>
    <div class="page__body container">
        <div class="mt-8">
            <form class="space-y-5 mt-5" method="POST"
                  action="{{ isset($person) ? route('person.update', $person->id) : route('person.store') }}">
                @csrf

                @if(isset($person))
                    @method('PUT')
                    <div class="block-news">
                        <h2>{{ __('admin/admin.name_person') . ': ' . $person->name}}</h2>
                        <p>{{__('admin/admin.email_person') . ': ' .$person->email}}</p>
                    </div>
                @else
                    <input name="name" type="text"
                           class="w-full h-12 border border-gray-800 rounded px-3 @error('name') border-red-500 @enderror"
                           placeholder="{{__('admin/admin.placeholder_name_person')}}" value="{{ $person->name ?? '' }}">
                    @error('name')
                    <p class="text-red-500">{{ $message }}</p>
                    @enderror

                    <input name="email" type="email"
                           class="w-full h-12 border border-gray-800 rounded px-3 @error('title') border-red-500 @enderror"
                           placeholder="{{__('admin/admin.placeholder_email')}}" value="{{ $person->email ?? '' }}">
                    @error('email')
                    <p class="text-red-500">{{ $message }}</p>
                    @enderror

                    <input name="password" type="password"
                           class="w-full h-12 border border-gray-800 rounded px-3 @error('title') border-red-500 @enderror"
                           placeholder="{{__('admin/admin.placeholder_password')}}">
                    @error('password')
                    <p class="text-red-500">{{ $message }}</p>
                    @enderror
                @endif


                <input name="role" type="text"
                       class="w-full h-12 border border-gray-800 rounded px-3 @error('name') border-red-500 @enderror"
                       placeholder="{{__('admin/admin.placeholder_role')}}"
                       value="{{ isset($person) ? $person->getRoleNames()[0] : '' }}">
                @error('role')
                <p class="text-red-500">{{ $message }}</p>
                @enderror


                <button type="submit" class="text-center w-full bg-blue-900 rounded-md text-white py-3 font-medium"
                        value="save">
                    {{__('admin/buttons.button_save')}}
                </button>
            </form>
        </div>

        <div class="transition">
            <a href="{{route('person.index')}}" class="transition-button">
                <span class="transition-button__text">{{__('admin/buttons.button_back')}}</span>
            </a>
        </div>
    </div>

@endsection

resources/views/admin/news.blade.php
@extends('layouts.app')

@section('content')
    <div class="introduction">
        <div class="introduction__item container">
            <h1 class="introduction__title">{{ __('admin/admin.title_news') }}</h1>
        </div>
    </div>

    <div class="page__body container">
        <a href="{{ route('news.create') }}" class="transition-button">
            <span class="transition-button__text">{{ __('admin/buttons.button_add') }}</span>
        </a>
        <section class="news">
            @foreach($news as $item)
                <div class="block-news">
                    <a href="{{ route('news.show', $item->id) }}">
                        <h2>{{$item->title}}</h2>
                        <p> {{$item->description}}</p>
                    </a>
                </div>
            @endforeach
            {{ $news->links() }}
        </section>
    </div>
@endsection

resources/views/admin/oneNews.blade.php
@extends('layouts.app')

@section('content')
    <div class="introduction">
        <div class="introduction__item container">
            <h1 class="introduction__title">{{ $news->title }}</h1>
        </div>
    </div>

    <div class="page__body container">
        <section class="news">
            <div class="block-news">
                <h2>{{$news->title}}</h2>
                <p> {{$news->description}}</p>
                <p class="block-news__text">{{$news->news_body}}</p>
            </div>
            <div class="action">
                <a href="{{ route('news.edit', $news->id) }}" class="transition-button">
                    <span class="transition-button__text">{{__('admin/buttons.button_edit')}}</span>
                </a>

                <form action="{{ route('news.destroy', $news->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="transition-button">{{__('admin/buttons.button_del')}}</button>
                </form>
            </div>

            <div class="transition">
                <a href="{{route('news.index')}}" class="transition-button">
                    <span class="transition-button__text">{{__('admin/buttons.button_back_index')}}</span>
                </a>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/person.blade.php
@extends('layouts.app')

@section('content')
    <div class="introduction">
        <div class="introduction__item container">
            <h1 class="introduction__title">{{__('admin/admin.title_person')}}</h1>
        </div>
    </div>

    <div class="page__body container">
        <a href="{{ route('person.create') }}" class="transition-button">
            <span class="transition-button__text">{{ __('admin/buttons.button_add') }}</span>
        </a>
        <section class="news">
            @foreach($person as $user)
                <div class="block-news">
                    <h2>{{$user->name}}</h2>
                    @if(!empty($user->getRoleNames()))
                        <p>{{ $user->getRoleNames()[0] }}</p>
                    @endif
                    <div class="action">
                        <a href="{{ route('person.edit', $user->id) }}" class="transition-button">
                            <span class="transition-button__text">{{__('admin/buttons.button_edit')}}</span>
                        </a>

                        <form action="{{ route('person.destroy', $user->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="transition-button">{{__('admin/buttons.button_del')}}</button>
                        </form>
                    </div>
                </div>
            @endforeach
                {{ $person->links() }}
        </section>
    </div>
@endsection